# Sorting

In [1]:
import time
import numpy as np
np.random.seed(0)

In [2]:
data = np.random.randint(1,10000,17000)

### Insertion Sort

In [3]:
def insertion_sort(arr):
    start = time.time()
    for i in np.arange(1,len(arr)):
        look = arr[i]
        for j in np.arange(i-1,-1,-1):
          if look > arr[j]:
            break;
          else:
            arr[j+1] = arr[j]
            arr[j]   = look
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [4]:
arr= insertion_sort(data)

The time of execution of above program is : 31712.64338493347 ms for a size of  17000


In [5]:
arr

array([   1,    1,    1, ..., 9999, 9999, 9999])

### Merge Sort

In [6]:
def merge(left,right):
    new_arr = np.zeros(len(left)+len(right))
    for i in np.arange(0,len(new_arr)):
        if len(left) == 0:
            new_arr[i:] = right
            break;
        elif len(right) == 0:
            new_arr[i:] = left
            break;
        elif left[0]<right[0]:
            new_arr[i], left = left[0], left[1:]
        else:
            new_arr[i], right = right[0], right[1:]
    return new_arr

In [7]:
#This method is just to calculate the time, if you don't need it, don't worry
def merge_algorithm(arr):
    start = time.time()
    lists = []
    new_lists =[]
    for element in arr: #O(n) space complexity
        lists = lists+[np.array([element])]
    while len(lists) != 1:
        if np.mod(len(lists),2)==0:
            for i in np.arange(0,len(lists),2):
                new_lists = new_lists + [merge(lists[i],lists[i+1])]
        else:
            for i in np.arange(0,len(lists)-1,2):
                new_lists = new_lists + [merge(lists[i],lists[i+1])]
            new_lists = new_lists + [lists[-1]]
        lists = new_lists
        new_lists = []
    arr = np.array(lists[0])
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [8]:
prueba = np.array([3,2,5,8,1])
p = merge_algorithm(prueba)
print(p)

The time of execution of above program is : 0.0 ms for a size of  5
[1. 2. 3. 5. 8.]


In [9]:
data = np.random.randint(1,10000,17000)

In [10]:
merge_algorithm(data)

The time of execution of above program is : 594.9883460998535 ms for a size of  17000


array([1.000e+00, 3.000e+00, 4.000e+00, ..., 9.998e+03, 9.998e+03,
       9.998e+03])

### Algorithm of your choice

Know implement another algorithm, anyone works. Use the same size of data.

In [11]:
## School matrix multiplication
def school_product(M1,M2):
    M3 = np.zeros((np.shape(M1)[0],np.shape(M2)[1]))
    for i in np.arange(0,np.shape(M1)[0]):
        for j in np.arange(0,np.shape(M2)[1]):
            for k in np.arange(0,np.shape(M1)[1]): #O(n^3) complexity
                M3[i][j] += M1[i][k]*M2[k][j]
    return M3

In [12]:
size = 250
M1 = np.random.rand(size,size)
M2 = np.random.rand(size,size)
start = time.time()
school_product(M1,M2)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a pair of matrices with size ", size)

The time of execution of above program is : 10657.840251922607 ms for a pair of matrices with size  250


In [13]:
start = time.time()
np.matmul(M1,M2)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a pair of matrices with size ", size)

The time of execution of above program is : 8.012533187866211 ms for a pair of matrices with size  250


### Conclusions

So, the algorithm matters! Even when the result is the same, the time it takes is important. We are in the era of Big Data, if we are not careful, some processing might take centuries!